export const types = {
    PRODUCT_LIST_LOADING: 'PRODUCT_LIST_LOADING',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_ERROR: 'POKEMON_LIST_ERROR',

    PRODUCT_DETAILS_LOADING: 'PRODUCT_DETAILS_LOADING',
    PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
    PRODUCT_DETAILS_ERROR: 'PRODUCT_DETAILS_ERROR',
    
}