export const types = {
    USER_LOGIN_LOADING: 'USER_LOGIN_LOADING',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

    USER_LOGOUT: 'USER_LOGOUT',

    USER_REGISTER_LOADING: 'USER_REGISTER_LOADING',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_ERROR: 'USER_REGISTER_ERROR',
    
}