
    const products = [
        {
            '_id': '3',
            'name': '1080P HD Projector, WiFi Projector Bluetooth Projector, FANGOR 230" ',
            'image': 'https://m.media-amazon.com/images/I/81uo2jE8HFL._AC_SL1500_.jpg',
            'description': '【NATIVE 1080P FULL HD RESOLUTIONS】 With native resolution of 1920*1080 and contrast ratio of 10000:1, the Fangor-506 1080p Projector provides sharp and detailed HD images. Combining an innovative high-refraction 6 layers glassed lens, ensuring the best video experience.',
            'brand': 'FANGOR ',
            'category': 'Electronics',
            'price': 161.48,
            'countInStock': 10,
            'rating': 4.5,
            'numReviews': 12,
          },
          {
            '_id': '4',
            'name': 'Kindle Oasis – Now with adjustable warm light – Ad-Supported',
            'image': 'https://m.media-amazon.com/images/I/61moEqqnwzL._AC_SL1000_.jpg',
            'description': 'La luz frontal ajustable te permite leer cómodamente durante horas, en interiores y exteriores, de día y de noche.',
            'brand': 'Rad tech',
            'category': 'Electronics',
            'price': 128.99,
            'countInStock': 10,
            'rating': 4.5,
            'numReviews': 12,
          },
          {
            '_id': '5',
            'name': 'Ruko Smart Robots for Kids, Large Programmable Interactive',
            'image': 'https://m.media-amazon.com/images/I/616gY8nYY7L._AC_SL1280_.jpg',
            'description': 'Ruko Smart Robots for Kids, Large Programmable Interactive RC Robot with Voice Control, APP Control, Present for 4 5 6 7 8 9 Years Old Kids Boys and Girls',
            'brand': 'Apple',
            'category': 'Electronics',
            'price': 239.00,
            'countInStock': 10,
            'rating': 4.5,
            'numReviews': 12,
          },
          {
            '_id': '6',
            'name': 'Amazon Fire TV 55" 4-Series 4K UHD smart TVs',
            'image': 'https://m.media-amazon.com/images/I/51EPd38RHQL._AC_SL1000_.jpg',
            'description': 'Brilliant 4K entertainment - Bring movies and shows to life with support for vivid 4K Ultra HD, HDR 10, HLG, and Dolby Digital Plus.',
            'brand': 'Apple',
            'category': 'Tv',
            'price': 6594.99,
            'countInStock': 10,
            'rating': 4.5,
            'numReviews': 12,
          },
          {
            '_id': '3',
            'name': 'Ruko Smart Robots for Kids, Large Programmable Interactive',
            'image': 'https://m.media-amazon.com/images/I/616gY8nYY7L._AC_SL1280_.jpg',
            'description': 'Ruko Smart Robots for Kids, Large Programmable Interactive RC Robot with Voice Control, APP Control, Present for 4 5 6 7 8 9 Years Old Kids Boys and Girls',
            'brand': 'Apple',
            'category': 'Electronics',
            'price': 239.00,
            'countInStock': 10,
            'rating': 4.5,
            'numReviews': 12,
          },
          {
            '_id': '3',
            'name': 'Ruko Smart Robots for Kids, Large Programmable Interactive',
            'image': 'https://m.media-amazon.com/images/I/616gY8nYY7L._AC_SL1280_.jpg',
            'description': 'Ruko Smart Robots for Kids, Large Programmable Interactive RC Robot with Voice Control, APP Control, Present for 4 5 6 7 8 9 Years Old Kids Boys and Girls',
            'brand': 'Apple',
            'category': 'Electronics',
            'price': 239.00,
            'countInStock': 10,
            'rating': 4.5,
            'numReviews': 12,
          },
          {
            '_id': '3',
            'name': 'Ruko Smart Robots for Kids, Large Programmable Interactive',
            'image': 'https://m.media-amazon.com/images/I/616gY8nYY7L._AC_SL1280_.jpg',
            'description': 'Ruko Smart Robots for Kids, Large Programmable Interactive RC Robot with Voice Control, APP Control, Present for 4 5 6 7 8 9 Years Old Kids Boys and Girls',
            'brand': 'Apple',
            'category': 'Electronics',
            'price': 239.00,
            'countInStock': 10,
            'rating': 4.5,
            'numReviews': 12,
          },
          {
            '_id': '3',
            'name': 'Ruko Smart Robots for Kids, Large Programmable Interactive',
            'image': 'https://m.media-amazon.com/images/I/616gY8nYY7L._AC_SL1280_.jpg',
            'description': 'Ruko Smart Robots for Kids, Large Programmable Interactive RC Robot with Voice Control, APP Control, Present for 4 5 6 7 8 9 Years Old Kids Boys and Girls',
            'brand': 'Apple',
            'category': 'Electronics',
            'price': 239.00,
            'countInStock': 10,
            'rating': 4.5,
            'numReviews': 12,
          },
    ]

    export default products;